# Generated by Django 5.2.11 on 2026-03-18 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="文章ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文章标题")),
                (
                    "cover_image",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="封面图URL"
                    ),
                ),
                ("content", models.TextField(verbose_name="文章内容")),
                (
                    "author",
                    models.CharField(
                        default="心理中心", max_length=50, verbose_name="作者/机构"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="published", max_length=20, verbose_name="发布状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "biz_article",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentScale",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="量表ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="量表名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="量表指导语"),
                ),
                (
                    "question_count",
                    models.IntegerField(default=0, verbose_name="题目总数"),
                ),
                (
                    "scoring_rules",
                    models.JSONField(default=list, verbose_name="计分与评级规则"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "biz_assessment_scale",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(verbose_name="题号")),
                ("content", models.CharField(max_length=500, verbose_name="题干内容")),
                ("options", models.JSONField(verbose_name="选项与分值")),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="apps.assessmentscale",
                    ),
                ),
            ],
            options={
                "db_table": "biz_assessment_question",
                "ordering": ["sort_order"],
            },
        ),
    ]
