# Generated by Django 5.2.11 on 2026-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_article_assessmentscale_assessmentquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrisisKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="关键词/正则"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("critical", "极高危 (直接拦截)"),
                            ("sensitive", "敏感 (告警/关注)"),
                        ],
                        default="critical",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "违规关键词",
                "verbose_name_plural": "违规关键词",
                "db_table": "sec_crisis_keyword",
                "ordering": ["-created_at"],
            },
        ),
    ]
