# Generated by Django 5.2.11 on 2026-03-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_crisiskeyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="等级名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="等级描述"),
                ),
                (
                    "score_range",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="得分范围"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#67C23A", max_length=20, verbose_name="显示颜色"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
            ],
            options={
                "verbose_name": "风险等级",
                "verbose_name_plural": "风险等级",
                "db_table": "sec_risk_level",
            },
        ),
        migrations.CreateModel(
            name="EmergencyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="预案标题")),
                ("content", models.TextField(verbose_name="干预内容/资源描述")),
                (
                    "contacts",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="联系电话/机构",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        default="GENERAL", max_length=50, verbose_name="适用领域"
                    ),
                ),
                (
                    "risk_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="apps.risklevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "紧急预案",
                "verbose_name_plural": "紧急预案",
                "db_table": "sec_emergency_plan",
            },
        ),
    ]
