# Generated by Django 5.2.11 on 2026-03-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_alter_crisiskeyword_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crisiskeyword",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="apps.risklevel",
                verbose_name="风险等级",
            ),
        ),
    ]
