# Generated by Django 5.2.11 on 2026-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_alter_crisiskeyword_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidanceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="引导问题")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "通用"),
                            ("freshman", "新生适应"),
                            ("academic", "学业压力"),
                            ("emotion", "情绪困扰"),
                            ("relationship", "人际关系"),
                            ("career", "就业规划"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="问题类别",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="💬", max_length=50, verbose_name="图标标识"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="数值越大越靠前", verbose_name="排序权重"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "引导问题",
                "verbose_name_plural": "引导问题",
                "db_table": "biz_guidance_question",
                "ordering": ["-sort_order", "-created_at"],
            },
        ),
    ]
