# Generated by Django 5.2.11 on 2026-04-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_guidancequestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guidancequestion",
            name="icon",
        ),
    ]
