# Generated by Django 5.2.11 on 2026-04-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_remove_guidancequestion_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="knowledge_base_uuid",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="关联知识库UUID"
            ),
        ),
    ]
