# Generated by Django 5.2.11 on 2026-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0010_chatmessage_knowledge_base_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestion",
            name="dimension",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="所属维度"
            ),
        ),
        migrations.AddField(
            model_name="assessmentrecord",
            name="dimension_scores",
            field=models.JSONField(blank=True, null=True, verbose_name="各维度得分"),
        ),
        migrations.AlterField(
            model_name="assessmentquestion",
            name="content",
            field=models.TextField(verbose_name="题干内容"),
        ),
    ]
