# Generated by Django 5.2.11 on 2026-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_assessmentquestion_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="suggested_assessment",
            field=models.JSONField(blank=True, null=True, verbose_name="测评建议数据"),
        ),
    ]
