# Generated by Django 5.2.11 on 2026-04-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0013_articlecomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.AddField(
            model_name="emergencyplan",
            name="action_type",
            field=models.CharField(
                default="display_card", max_length=50, verbose_name="动作类型"
            ),
        ),
        migrations.AddField(
            model_name="emergencyplan",
            name="template_name",
            field=models.CharField(
                default="default", max_length=100, verbose_name="渲染模板"
            ),
        ),
    ]
