# Generated by Django 5.2.11 on 2026-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0014_alter_chatsession_options_emergencyplan_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyplan",
            name="button_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="按钮文案"
            ),
        ),
        migrations.AddField(
            model_name="emergencyplan",
            name="scale_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="关联量表ID"
            ),
        ),
    ]
