# Generated by Django 5.2.11 on 2026-05-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_emergencyplan_button_text_emergencyplan_scale_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crisisalertlog",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crisis_alerts",
                to="apps.chatmessage",
            ),
        ),
    ]
